# Generated by Django 4.2.1 on 2023-05-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=100)),
                ("datetime", models.DateTimeField()),
                ("headline", models.CharField(max_length=500)),
                ("news_id", models.IntegerField()),
                ("image", models.TextField()),
                ("related", models.CharField(max_length=50)),
                ("source", models.CharField(max_length=100)),
                ("summary", models.TextField()),
                ("url", models.TextField()),
            ],
        ),
    ]
