# Generated by Django 4.2.1 on 2023-05-06 10:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("market_news", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="news",
            table='"market_news"',
        ),
    ]
